project1/project1_lecture/hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("brian", views.brian, name="brian"),
    path("<str:name>", views.greet, name="greet")
]

project1/project1_lecture/newyear/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
]

project1/project1_lecture/project1_lecture/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', include("hello.urls")),
    path('newyear/', include("newyear.urls")),
    path('tasks/', include("tasks.urls"))
]

project1/project1_lecture/tasks/urls.py
from django.urls import path
from . import views

app_name = "tasks"
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name="add"),
    path("add2", views.add2, name="add2")
]

project1/project1_lecture/hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, "hello/index.html")

def brian(request):
    return HttpResponse("Hello, Brian!")

def greet(request, name):
    return render(request, "hello/greet.html", {
        "name": name.capitalize()
    })

project1/project1_lecture/newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
    now = datetime.datetime.now()
    return render(request, "newyear/index.html", {
        "newyear": now.month == 1 and now.day == 1,
        "now": now
    })

project1/project1_lecture/tasks/views.py
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


class NewTaskForm(forms.Form):
    task = forms.CharField(label="New Task")
    priority = forms.IntegerField(label="Priority", min_value=1, max_value=5)

# Create your views here.
def index(request):
    if "tasks" not in request.session:
        request.session["tasks"] = []
    return render(request, "tasks/index.html", {
        "tasks": request.session["tasks"]
    })

def add(request):
    return render(request, "tasks/add.html")

def add2(request):
    if request.method == "POST":
        form = NewTaskForm(request.POST)
        if form.is_valid():
            task = form.cleaned_data["task"]
            request.session["tasks"] += [task]
            return HttpResponseRedirect(reverse("tasks:index"))
        else:
            return render(request, "tasks/add2.html", {
                "form": form
            })

    return render(request, "tasks/add2.html", {
        "form": NewTaskForm()
    })

project1/project1_lecture/hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Greet</title>
</head>
<body>
    <h1>Hello, {{ name }}</h1>
</body>
</html>

project1/project1_lecture/hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Hello</title>
</head>
<body>
    <h1>Hello, world!</h1>
</body>
</html>

project1/project1_lecture/newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Newyear</title>

    <link href="{% static 'newyear/styles.css' %}" rel="stylesheet">
</head>
<body>
    {% if newyear %}
        <h1>YES</h1>
    {% else %}
        <h1>NO</h1>
    {% endif %}
    <br><br>
    <h2>{{ now }}</h2>
</body>
</html>

project1/project1_lecture/tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body %}
    <a href="{% url 'tasks:index' %}">View Tasks</a>
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add' %}" method="post">
        {% csrf_token %}
        <input type="text", name="task">
        <input type="submit">
    </form>
{% endblock %}

project1/project1_lecture/tasks/templates/tasks/add2.html
{% extends "tasks/layout.html" %}

{% block body %}
    <a href="{% url 'tasks:index' %}">View Tasks</a>
    <h1>Add Task</h1>
    <form action="{% url 'tasks:add2' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

project1/project1_lecture/tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
    <a href="{% url 'tasks:add' %}">Add Task</a>
    <a href="{% url 'tasks:add2' %}">Add Task 2</a>
    <h1>Tasks:</h1>
    <ul>
        {% for task in tasks %}
            <li>{{ task }}</li>
        {% empty %}
            <li>No tasks</li>
        {% endfor %}
    </ul>
{% endblock %}

project1/project1_lecture/tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>